version: '2'
services:
  cacti_mysql:
    image: mariadb
    container_name: cacti_mysql
    hostname: cacti_mysql
    ports:
      - 3306
    volumes:
      - ${COMPOSEROOT}/cacti/data/mysql:/var/lib/mysql
    env_file: .env

  cacti:
    depends_on: 
      - cacti_mysql
    image: twhtanghk/cacti
    container_name: cacti
    hostname: cacti
    links:
      - cacti_mysql
    ports:
      - 80
    volumes:
      - ${COMPOSEROOT}/cacti/conf/php.ini:/usr/local/etc/php/php.ini
      - ${COMPOSEROOT}/cacti/conf/config.php:/var/www/html/cacti/include/config.php
      - ${COMPOSEROOT}/cacti/data/rra:/var/www/html/cacti/rra
    env_file: .env
